[package]
name = "we-cluster-rs"
version = "0.0.1"
edition = "2024"
authors = ["NuageImprudent"]
license = "MIT"
description = "A simple Rust implementation of we speaker clusterization"
repository = "https://github.com/NuageImprudent/we-cluster-rs"

[dependencies]
ndarray = "0.16.1"
rand = "0.8"
thiserror = "1.0"
hdbscan = "0.12"
itertools = "0.14.0"
anyhow = "1.0.100"
